### ISSUE TITLE
Can't install rstudio server for ubuntu 22.04

### ISSUE THREAD

**Issue by zaro0508** [Oefenweb/ansible-rstudio-server#15]
I would like to install a version of rstudio server for ubuntu 22.04 (jammy jellyfish) from the [posit download link](https://download2.rstudio.org/server/jammy/amd64/rstudio-server-2023.03.1-446-amd64.deb).  I tried to install with the following  ansible task however it doesn't seem to work.

```
tasks:
    - name: Install Rstudio Server
      ansible.builtin.import_role:
        name: oefenweb.rstudio_server
      vars:
        rstudio_server_download_url: "https://download2.rstudio.org/server/jammy/amd64/rstudio-server-2023.03.1-446-amd64.deb"
```

I get the following error..
```
[default] => (item=/Users/zaro0508/.ansible/roles/oefenweb.rstudio_server/vars/_default.yml) => 
{
  "ansible_facts": {
    "rstudio_server_download_url": "https://download2.rstudio.org/server/bionic/{{ rstudio_server_machine_map[ansible_machine] }}/rstudio-server-{{ rstudio_server_version }}-{{ rstudio_server_machine_map[ansible_machine] }}.deb"
  },
  "ansible_included_var_files": [
    "/Users/zaro0508/.ansible/roles/oefenweb.rstudio_server/vars/_default.yml"
  ],
  "ansible_loop_var": "item",
  "changed": false,
  "item": "/Users/zaro0508/.ansible/roles/oefenweb.rstudio_server/vars/_default.yml"
}
```

it looks like the download url is hard coded to `https://download2.rstudio.org/server/bionic/` which is for `bionic`?  Would it be possible to support later versions?
